print("-------------------------------------------------FIRST OF AUGEST WEEK MONDAY TO FRIDAY TASKES-----------------------------------------------")
print("MONDAY: camping whole day")
print("TUESDAY: Making sure I have all school supplices")
print("WEDNESDAY: movies and baseball")
print("THURSDAY: First day of school")
print("FRIDAY: second shot for covid")